### ISSUE TITLE
Обновление списка корзины

### ISSUE THREAD

**Issue by VZhyrytskiy** [AlenaBahatka/shop#4]
Ответ на вопрос:
В последнем задании при добавлении кастомного пайпа, заметила, что если для выбора типа сортировки(возрастание/убывание) использовать выпадающий список(true/false опции), то обновляется list быстрее  чем, если использовать чекбокс.
Я не уверена, возможно мне кажется, а возможно что-то за этим скрывается, что я не знаю. Мб вы знаете в чем дело? 

Обновление происходит, как только появляется асинхронная операция. В вашем случае это обзервбл, который предоставляет данные каждые 5с. Чтобы обновление проходило тогда, когда вы кликаете на чекбокс, необходимо добавить пустой обработчик события <input #descAsc id="descAsc" type="checkbox" (change)="0"> Это нужно, чтобы сразу после изменения ангуляр запустил обнаружение изменений. Делать это надо только, когда используете #descAsc. Не самый лучший вариант. У нас впереди будет тема по формам. Мы там расмотрим альтернативные варианты.

**Comment by AlenaBahatka** [comment]
Спасибо за пояснение. Исправила и теперь все работает куда лучше) https://github.com/AlenaBahatka/shop/commit/2b3b0452b592a59410b6ad54bc5d2fbb04ee3ce6
