### ISSUE TITLE
Циклические зависимости

### ISSUE THREAD

**Issue by VZhyrytskiy** [AlenaBahatka/shop#5]
Во время компиляции появляются сообщения
Надо просмотреть где вы использовали index.ts. Скорее всего он включает файл, а в файле вы ссылаетесь на папку.

WARNING in Circular dependency detected:
src\app\products\index.ts -> src\app\products\product-form\product-form.component.ts -> src\app\products\index.ts

WARNING in Circular dependency detected:
src\app\products\product-form\product-form.component.ts -> src\app\products\index.ts -> src\app\products\product-form\product-form.component.ts

WARNING in Circular dependency detected:
src\app\products\product-list\product-list.component.ts -> src\app\products\index.ts -> src\app\products\product-list\product-list.component.ts

**Comment by AlenaBahatka** [comment]
ага..спасибо! 
нельзя видимо index.ts использовать в тех компонентах которые в него же и входят. починила: https://github.com/AlenaBahatka/shop/commit/02ae32c60c8fb3c067f511578d2fd5aebb916338
